"""
orchestrator/session_manager_schemas.py
Pydantic schemas for Session Manager input/output.

This defines the interface between the API layer and the Session Manager.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from uuid import UUID
from datetime import datetime


class SessionManagerRequest(BaseModel):
    """
    Request from user to Session Manager.

    This is what the API receives from the frontend/user.
    """
    session_id: UUID = Field(..., description="Unique session identifier")
    message: str = Field(..., description="User's message or input")

    class Config:
        json_schema_extra = {
            "example": {
                "session_id": "cca3e1e3-7de9-43ee-b471-ff817b4b8537",
                "message": "I'm ready to begin"
            }
        }


class LibraryItemResponse(BaseModel):
    """
    A single piece of content from the library.

    This is what gets presented to the user.
    """
    kind: str = Field(..., description="Type of content (script, prompt, etc)")
    title: str = Field(..., description="Title of the content")
    body: str = Field(..., description="Full content text")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata")


class StateInfo(BaseModel):
    """Information about the current state."""
    state_id: UUID = Field(..., description="UUID of current state")
    state_code: str = Field(..., description="Code of current state (e.g., calm_welcome)")
    state_name: str = Field(..., description="Display name of current state")


class SessionManagerResponse(BaseModel):
    """
    Response from Session Manager to user.

    This is what gets returned to the frontend/user.
    """
    session_id: UUID = Field(..., description="Session identifier")
    current_state: StateInfo = Field(..., description="Current state information")
    ### RItesh Oraon ###
    process_text: str = Field(..., description="Process being followed")
    ####################

    # Content to present to user
    content: List[LibraryItemResponse] = Field(
        default_factory=list,
        description="Library items (scripts/prompts) to present to user"
    )

    # LLM-generated personalized response
    llm_response: Optional[str] = Field(
        default=None,
        description="Personalized response generated by Claude LLM based on context"
    )

    # Session metadata
    message_count: int = Field(..., description="Total messages in session")
    started_at: datetime = Field(..., description="When session started")

    # Transition info (for debugging/logging)
    transition_taken: Optional[str] = Field(
        default=None,
        description="Description of which transition was taken (debug info)"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "session_id": "cca3e1e3-7de9-43ee-b471-ff817b4b8537",
                "current_state": {
                    "state_id": "4b25bfed-6f04-4d20-8f0f-7497b623e19d",
                    "state_code": "calm_breath_observation",
                    "state_name": "Observe Your Breath"
                },
                "process_text":"Breathing init",
                "content": [
                    {
                        "kind": "script",
                        "title": "Observe Your Breath - Guided Script",
                        "body": "Take a comfortable position and gently bring your attention...",
                        "metadata": {"intent": "calm", "technique": "anchor_word_breathing"}
                    }
                ],
                "message_count": 1,
                "started_at": "2026-05-12T20:37:39.342968+00:00",
                "transition_taken": "calm_welcome → calm_breath_observation"
            }
        }

        ## Ritesh Oraon ##
        #"process_text":"Breathing init",
        ####################################
